version: "3.9"
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    networks:
      - backend

  redis:
    image: redis:6.0.15-alpine3.14
    depends_on: 
      - mysql
    networks:
      - backend

  php:
    build: ./php
    depends_on:
      - redis
      - mysql
    networks:
      - backend
    
  nginx:
    build: ./nginx
    ports:
      - "5000:80"
    depends_on: 
      - redis
      - mysql
      - php
    networks:
      - frontend
      - backend
    links:
      - "php:php-app"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
